import sys  
sys.path.insert(0, 'F:/Multimodel/backend')  
"from app.database import init_db, engine, _migrate_schema, Base"  
"from sqlalchemy import inspector"  
""  
"print('=' * 60)"  
"print('FINAL VALIDATION TESTS')"  
"print('=' * 60)"  
""  
"print('\\n--- Test 1: Database Migration ---')"  
"_migrate_schema()"  
"inspector = inspector(engine)"  
"existing_cols = {c['name'] for c in inspector.get_columns('patients')}"  
"print(f'Patients columns: {sorted(existing_cols)}')"  
""  
"assert 'created_at' in existing_cols, 'FAIL: created_at missing!'"  
"assert 'updated_at' in existing_cols, 'FAIL: updated_at missing!'"  
"print('PASS: Both created_at and updated_at exist in patients table')"  
""  
"print('\\n--- Test 2: Backend Startup ---')"  
"init_db()"  
"print('PASS: init_db() ran successfully')"  
""  
"print('\\n' + '=' * 62)"  
"print('DATABASE TESTS PASSED')"  
"print('=' * 62)" 
